const topData = [
    {
      top: 1,
      title: "Undead Unluck",
      author: "Yoshifumi Tozuka",
      image: require("../assets/undeadBanner.png"),
    },
    {
      top: 2,
      title: "Sakamoto Days",
      author: "Yuto Suzuki",
      image: require("../assets/sakamotoBanner.png"),
    },
    {
      top: 3,
      title: "One Piece",
      author: "Eiichiro Oda",
      image: require("../assets/onepieceBanner.png"),
    },
    {
      top: 4,
      title: "Jujutsu Kaisen",
      author: "Gege Akutami",
      image: require("../assets/jujutsuBanner.png"),
    },
    {
      top: 5,
      title: "Boku no Hero Academia",
      author: "Kohei Horikoshi",
      image: require("../assets/myheroBanner.png"),
    },
  ];
const data = [
    {
        id:1,
        title: "Beserk",
        author: "Miura, Kentarou",
        ch: 388,
        image: require("../assets/berserk.png"),
        synopsis:'After a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya memberAfter a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya member',
        rate:8.32,
        genre:['Action','Adventure','Fantasy'],
        read: [require("../assets/read1.png"),require("../assets/read2.png"),require("../assets/read3.png"),require("../assets/read4.png"),require("../assets/read5.png"),require("../assets/read6.png"),require("../assets/read7.png")],
      },
      {
        id:2,
        title: "Chainsaw Man",
        author: "Yuto Suzuki",
        ch: 104,
        image: require("../assets/chainsaw.png"),
        synopsis:'After a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya memberAfter a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya member',
        rate:8.32,
        genre:['Action', 'Adventure','Fantasy','Psychological'],
        read: [require("../assets/read1.png"),require("../assets/read2.png"),require("../assets/read3.png"),require("../assets/read4.png"),require("../assets/read5.png"),require("../assets/read6.png"),require("../assets/read7.png")],
      },
      {
        id:3,
        title: "Demon Slayer",
        author: "Koyoharu Gotouge",
        ch: 205,
        image: require("../assets/demon.png"),
        synopsis:'After a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya memberAfter a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya member',
        rate:8.32,
        genre:['Action', 'Adventure','Fantasy','Slice of Life','Romance','Comedy'],
        read: [require("../assets/read1.png"),require("../assets/read2.png"),require("../assets/read3.png"),require("../assets/read4.png"),require("../assets/read5.png"),require("../assets/read6.png"),require("../assets/read7.png")],
      },
      {
        id:4,
        title: "SPY x FAMILY",
        author: "Tatsuya Endo",
        ch: 201,
        image: require("../assets/spy.png"),
        synopsis:'After a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya memberAfter a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya member',
        rate:8.32,
        genre:['Action', 'Adventure','Comedy','Slice of Life','Romance','Drama'],
        read: [require("../assets/read1.png"),require("../assets/read2.png"),require("../assets/read3.png"),require("../assets/read4.png"),require("../assets/read5.png"),require("../assets/read6.png"),require("../assets/read7.png")],
      },
      {
        id:5,
        title: "Hunter x Hunter",
        author: "Yoshihiro Togashi",
        ch: 678,
        image: require("../assets/hunter.png"),
        synopsis:'After a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya memberAfter a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya member',
        rate:8.32,
        genre:['Action', 'Adventure','Comedy','Magic','Fantasy'],
        read: [require("../assets/read1.png"),require("../assets/read2.png"),require("../assets/read3.png"),require("../assets/read4.png"),require("../assets/read5.png"),require("../assets/read6.png"),require("../assets/read7.png")],
    },
  ];
  export{data,topData}